name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  run-terraform:
    name: 'Run terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup terraform
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check
      
      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve